/**
 * Pre-defined goal templates for common objectives
 * Helps users quickly create goals
 */

import { getGoalTemplateTranslation, Language } from '../i18n/template-translations';
import { GoalTemplate } from '../types';

const GOAL_TEMPLATES_BASE: GoalTemplate[] = [
  // Health & Fitness
  {
    id: 'lose_weight',
    title: 'Lose Weight',
    category: 'fitness',
    description: 'Reach your target weight',
    target: 70,
    unit: 'kg',
    direction: 'decrease',
    points: 100,
    period: 'monthly',
    icon: '⚖️',
  },
  {
    id: 'gain_muscle',
    title: 'Build Muscle',
    category: 'fitness',
    description: 'Increase muscle mass',
    target: 75,
    unit: 'kg',
    direction: 'increase',
    points: 100,
    period: 'monthly',
    icon: '💪',
  },
  {
    id: 'run_distance',
    title: 'Run Distance',
    category: 'fitness',
    description: 'Complete running goal',
    target: 100,
    unit: 'km',
    direction: 'increase',
    points: 50,
    period: 'monthly',
    icon: '🏃',
  },
  {
    id: 'daily_water',
    title: 'Drink Water',
    category: 'health',
    description: 'Stay hydrated daily',
    target: 8,
    unit: 'glasses',
    direction: 'increase',
    points: 10,
    period: 'daily',
    icon: '💧',
  },
  {
    id: 'workout_streak',
    title: 'Workout Routine',
    category: 'fitness',
    description: 'Exercise regularly',
    target: 30,
    unit: 'workouts',
    direction: 'increase',
    points: 75,
    period: 'monthly',
    icon: '🏋️',
  },
  
  // Learning & Education
  {
    id: 'read_books',
    title: 'Reading Challenge',
    category: 'learning',
    description: 'Read more books',
    target: 12,
    unit: 'books',
    direction: 'increase',
    points: 100,
    period: 'yearly',
    icon: '📚',
  },
  {
    id: 'learn_language',
    title: 'Language Practice',
    category: 'learning',
    description: 'Practice new language daily',
    target: 30,
    unit: 'minutes',
    direction: 'increase',
    points: 20,
    period: 'daily',
    icon: '🗣️',
  },
  {
    id: 'online_courses',
    title: 'Complete Courses',
    category: 'learning',
    description: 'Finish online courses',
    target: 5,
    unit: 'courses',
    direction: 'increase',
    points: 150,
    period: 'yearly',
    icon: '🎓',
  },
  
  // Finance
  {
    id: 'save_money',
    title: 'Build Savings',
    category: 'finance',
    description: 'Reach savings goal',
    target: 10000,
    unit: 'dollars',
    direction: 'increase',
    points: 200,
    period: 'yearly',
    icon: '💰',
  },
  {
    id: 'reduce_debt',
    title: 'Pay Off Debt',
    category: 'finance',
    description: 'Reduce total debt',
    target: 0,
    unit: 'dollars',
    direction: 'decrease',
    points: 250,
    period: 'yearly',
    icon: '💳',
  },
  {
    id: 'invest',
    title: 'Investment Goal',
    category: 'finance',
    description: 'Build investment portfolio',
    target: 5000,
    unit: 'dollars',
    direction: 'increase',
    points: 150,
    period: 'yearly',
    icon: '📈',
  },
  
  // Work & Productivity
  {
    id: 'complete_projects',
    title: 'Finish Projects',
    category: 'work',
    description: 'Complete work projects',
    target: 10,
    unit: 'projects',
    direction: 'increase',
    points: 100,
    period: 'monthly',
    icon: '📋',
  },
  {
    id: 'reduce_distractions',
    title: 'Focus Time',
    category: 'work',
    description: 'Reduce screen time',
    target: 2,
    unit: 'hours',
    direction: 'decrease',
    points: 50,
    period: 'daily',
    icon: '📱',
  },
  
  // Personal Development
  {
    id: 'meditation',
    title: 'Daily Meditation',
    category: 'personal',
    description: 'Practice mindfulness',
    target: 20,
    unit: 'minutes',
    direction: 'increase',
    points: 30,
    period: 'daily',
    icon: '🧘',
  },
  {
    id: 'sleep_better',
    title: 'Quality Sleep',
    category: 'health',
    description: 'Get enough sleep',
    target: 8,
    unit: 'hours',
    direction: 'increase',
    points: 25,
    period: 'daily',
    icon: '😴',
  },
  {
    id: 'journaling',
    title: 'Daily Journal',
    category: 'personal',
    description: 'Write in journal daily',
    target: 30,
    unit: 'entries',
    direction: 'increase',
    points: 40,
    period: 'monthly',
    icon: '📔',
  },
  
  // Social & Relationships
  {
    id: 'family_time',
    title: 'Family Time',
    category: 'social',
    description: 'Spend quality time with family',
    target: 10,
    unit: 'hours',
    direction: 'increase',
    points: 50,
    period: 'weekly',
    icon: '👨‍👩‍👧‍👦',
  },
  {
    id: 'meet_friends',
    title: 'Social Connection',
    category: 'social',
    description: 'Meet with friends regularly',
    target: 4,
    unit: 'times',
    direction: 'increase',
    points: 30,
    period: 'monthly',
    icon: '🤝',
  },
  
  // Hobbies & Creativity
  {
    id: 'creative_projects',
    title: 'Creative Work',
    category: 'hobby',
    description: 'Complete creative projects',
    target: 12,
    unit: 'projects',
    direction: 'increase',
    points: 80,
    period: 'yearly',
    icon: '🎨',
  },
  {
    id: 'learn_instrument',
    title: 'Practice Music',
    category: 'hobby',
    description: 'Practice musical instrument',
    target: 30,
    unit: 'minutes',
    direction: 'increase',
    points: 25,
    period: 'daily',
    icon: '🎸',
  },
  {
    id: 'photography',
    title: 'Photography Practice',
    category: 'hobby',
    description: 'Take photos regularly',
    target: 50,
    unit: 'photos',
    direction: 'increase',
    points: 40,
    period: 'weekly',
    icon: '📷',
  },
  {
    id: 'cooking',
    title: 'Cook New Recipes',
    category: 'hobby',
    description: 'Try new recipes at home',
    target: 20,
    unit: 'recipes',
    direction: 'increase',
    points: 60,
    period: 'monthly',
    icon: '👨‍🍳',
  },
  {
    id: 'gardening',
    title: 'Garden Work',
    category: 'hobby',
    description: 'Tend to garden regularly',
    target: 10,
    unit: 'hours',
    direction: 'increase',
    points: 35,
    period: 'monthly',
    icon: '🌱',
  },
  {
    id: 'writing',
    title: 'Creative Writing',
    category: 'hobby',
    description: 'Write creatively',
    target: 500,
    unit: 'words',
    direction: 'increase',
    points: 30,
    period: 'daily',
    icon: '✍️',
  },
  {
    id: 'drawing',
    title: 'Drawing Practice',
    category: 'hobby',
    description: 'Practice drawing skills',
    target: 30,
    unit: 'minutes',
    direction: 'increase',
    points: 25,
    period: 'daily',
    icon: '🖌️',
  },
  
  // More Fitness
  {
    id: 'steps_daily',
    title: 'Daily Steps',
    category: 'fitness',
    description: 'Walk 10,000 steps',
    target: 10000,
    unit: 'steps',
    direction: 'increase',
    points: 20,
    period: 'daily',
    icon: '👟',
  },
  {
    id: 'cycling',
    title: 'Cycling Distance',
    category: 'fitness',
    description: 'Cycle regularly',
    target: 100,
    unit: 'km',
    direction: 'increase',
    points: 60,
    period: 'weekly',
    icon: '🚴',
  },
  {
    id: 'swimming',
    title: 'Swimming Laps',
    category: 'fitness',
    description: 'Swim for fitness',
    target: 50,
    unit: 'laps',
    direction: 'increase',
    points: 40,
    period: 'weekly',
    icon: '🏊',
  },
  {
    id: 'yoga',
    title: 'Yoga Sessions',
    category: 'fitness',
    description: 'Practice yoga regularly',
    target: 20,
    unit: 'sessions',
    direction: 'increase',
    points: 50,
    period: 'monthly',
    icon: '🧘‍♀️',
  },
  {
    id: 'pushups',
    title: 'Push-ups Challenge',
    category: 'fitness',
    description: 'Complete daily push-ups',
    target: 50,
    unit: 'reps',
    direction: 'increase',
    points: 15,
    period: 'daily',
    icon: '💪',
  },
  {
    id: 'plank',
    title: 'Plank Time',
    category: 'fitness',
    description: 'Hold plank position',
    target: 5,
    unit: 'minutes',
    direction: 'increase',
    points: 20,
    period: 'daily',
    icon: '🏋️‍♀️',
  },
  
  // More Health
  {
    id: 'vegetables',
    title: 'Eat Vegetables',
    category: 'health',
    description: 'Daily vegetable servings',
    target: 5,
    unit: 'servings',
    direction: 'increase',
    points: 15,
    period: 'daily',
    icon: '🥗',
  },
  {
    id: 'reduce_sugar',
    title: 'Limit Sugar Intake',
    category: 'health',
    description: 'Reduce sugar consumption',
    target: 25,
    unit: 'grams',
    direction: 'decrease',
    points: 30,
    period: 'daily',
    icon: '🍬',
  },
  {
    id: 'vitamins',
    title: 'Take Vitamins',
    category: 'health',
    description: 'Daily vitamin routine',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 40,
    period: 'monthly',
    icon: '💊',
  },
  {
    id: 'reduce_caffeine',
    title: 'Limit Caffeine',
    category: 'health',
    description: 'Reduce coffee/energy drinks',
    target: 2,
    unit: 'cups',
    direction: 'decrease',
    points: 25,
    period: 'daily',
    icon: '☕',
  },
  {
    id: 'stretch',
    title: 'Daily Stretching',
    category: 'health',
    description: 'Stretch for flexibility',
    target: 15,
    unit: 'minutes',
    direction: 'increase',
    points: 15,
    period: 'daily',
    icon: '🤸',
  },
  {
    id: 'dental',
    title: 'Dental Care',
    category: 'health',
    description: 'Brush and floss daily',
    target: 2,
    unit: 'times',
    direction: 'increase',
    points: 10,
    period: 'daily',
    icon: '🦷',
  },
  
  // More Learning
  {
    id: 'podcasts',
    title: 'Listen to Podcasts',
    category: 'learning',
    description: 'Educational podcasts',
    target: 10,
    unit: 'episodes',
    direction: 'increase',
    points: 30,
    period: 'weekly',
    icon: '🎧',
  },
  {
    id: 'coding',
    title: 'Code Practice',
    category: 'learning',
    description: 'Practice programming',
    target: 2,
    unit: 'hours',
    direction: 'increase',
    points: 50,
    period: 'daily',
    icon: '💻',
  },
  {
    id: 'watch_tutorials',
    title: 'Watch Tutorials',
    category: 'learning',
    description: 'Learn from video tutorials',
    target: 5,
    unit: 'videos',
    direction: 'increase',
    points: 20,
    period: 'weekly',
    icon: '📺',
  },
  {
    id: 'practice_math',
    title: 'Math Practice',
    category: 'learning',
    description: 'Solve math problems',
    target: 20,
    unit: 'problems',
    direction: 'increase',
    points: 25,
    period: 'daily',
    icon: '🔢',
  },
  {
    id: 'vocabulary',
    title: 'Learn Vocabulary',
    category: 'learning',
    description: 'Learn new words',
    target: 100,
    unit: 'words',
    direction: 'increase',
    points: 60,
    period: 'monthly',
    icon: '📖',
  },
  {
    id: 'certifications',
    title: 'Get Certified',
    category: 'learning',
    description: 'Earn certifications',
    target: 3,
    unit: 'certs',
    direction: 'increase',
    points: 200,
    period: 'yearly',
    icon: '🎖️',
  },
  
  // More Work
  {
    id: 'emails',
    title: 'Clear Inbox',
    category: 'work',
    description: 'Reach inbox zero',
    target: 0,
    unit: 'emails',
    direction: 'decrease',
    points: 30,
    period: 'daily',
    icon: '📧',
  },
  {
    id: 'meetings',
    title: 'Limit Meetings',
    category: 'work',
    description: 'Reduce meeting time',
    target: 3,
    unit: 'hours',
    direction: 'decrease',
    points: 40,
    period: 'weekly',
    icon: '📅',
  },
  {
    id: 'networking',
    title: 'Network Growth',
    category: 'work',
    description: 'Connect with professionals',
    target: 20,
    unit: 'connections',
    direction: 'increase',
    points: 50,
    period: 'monthly',
    icon: '🤝',
  },
  {
    id: 'skills',
    title: 'Learn New Skills',
    category: 'work',
    description: 'Develop professional skills',
    target: 5,
    unit: 'skills',
    direction: 'increase',
    points: 100,
    period: 'yearly',
    icon: '🎯',
  },
  {
    id: 'presentations',
    title: 'Give Presentations',
    category: 'work',
    description: 'Present to teams',
    target: 12,
    unit: 'presentations',
    direction: 'increase',
    points: 80,
    period: 'yearly',
    icon: '📊',
  },
  
  // More Finance
  {
    id: 'emergency_fund',
    title: 'Emergency Fund',
    category: 'finance',
    description: 'Build emergency savings',
    target: 5000,
    unit: 'dollars',
    direction: 'increase',
    points: 150,
    period: 'yearly',
    icon: '🏦',
  },
  {
    id: 'reduce_expenses',
    title: 'Cut Expenses',
    category: 'finance',
    description: 'Lower monthly spending',
    target: 500,
    unit: 'dollars',
    direction: 'decrease',
    points: 100,
    period: 'monthly',
    icon: '📉',
  },
  {
    id: 'side_income',
    title: 'Side Income',
    category: 'finance',
    description: 'Earn extra money',
    target: 1000,
    unit: 'dollars',
    direction: 'increase',
    points: 120,
    period: 'monthly',
    icon: '💵',
  },
  {
    id: 'no_eat_out',
    title: 'Limit Dining Out',
    category: 'finance',
    description: 'Reduce restaurant spending',
    target: 10,
    unit: 'times',
    direction: 'decrease',
    points: 50,
    period: 'monthly',
    icon: '🍽️',
  },
  {
    id: 'budget_track',
    title: 'Track Budget',
    category: 'finance',
    description: 'Log daily expenses',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 40,
    period: 'monthly',
    icon: '📝',
  },
  
  // More Personal Development
  {
    id: 'gratitude',
    title: 'Gratitude Practice',
    category: 'personal',
    description: 'Write daily gratitude',
    target: 3,
    unit: 'items',
    direction: 'increase',
    points: 15,
    period: 'daily',
    icon: '🙏',
  },
  {
    id: 'morning_routine',
    title: 'Morning Routine',
    category: 'personal',
    description: 'Follow morning routine',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 50,
    period: 'monthly',
    icon: '🌅',
  },
  {
    id: 'no_social_media',
    title: 'Social Media Detox',
    category: 'personal',
    description: 'Reduce social media time',
    target: 30,
    unit: 'minutes',
    direction: 'decrease',
    points: 40,
    period: 'daily',
    icon: '📵',
  },
  {
    id: 'cold_shower',
    title: 'Cold Showers',
    category: 'personal',
    description: 'Take cold showers',
    target: 20,
    unit: 'showers',
    direction: 'increase',
    points: 35,
    period: 'monthly',
    icon: '🚿',
  },
  {
    id: 'affirmations',
    title: 'Daily Affirmations',
    category: 'personal',
    description: 'Practice positive affirmations',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 30,
    period: 'monthly',
    icon: '✨',
  },
  {
    id: 'declutter',
    title: 'Declutter Space',
    category: 'personal',
    description: 'Organize and clean',
    target: 4,
    unit: 'areas',
    direction: 'increase',
    points: 60,
    period: 'monthly',
    icon: '🧹',
  },
  
  // More Social
  {
    id: 'volunteer',
    title: 'Volunteer Work',
    category: 'social',
    description: 'Give back to community',
    target: 10,
    unit: 'hours',
    direction: 'increase',
    points: 80,
    period: 'monthly',
    icon: '🤲',
  },
  {
    id: 'call_family',
    title: 'Call Loved Ones',
    category: 'social',
    description: 'Stay connected with family',
    target: 5,
    unit: 'calls',
    direction: 'increase',
    points: 30,
    period: 'weekly',
    icon: '📞',
  },
  {
    id: 'make_friends',
    title: 'Expand Social Circle',
    category: 'social',
    description: 'Meet new people',
    target: 12,
    unit: 'people',
    direction: 'increase',
    points: 70,
    period: 'yearly',
    icon: '👋',
  },
  {
    id: 'compliments',
    title: 'Give Compliments',
    category: 'social',
    description: 'Spread positivity',
    target: 5,
    unit: 'compliments',
    direction: 'increase',
    points: 20,
    period: 'weekly',
    icon: '💝',
  },
  {
    id: 'help_others',
    title: 'Help Someone',
    category: 'social',
    description: 'Perform acts of kindness',
    target: 10,
    unit: 'acts',
    direction: 'increase',
    points: 50,
    period: 'monthly',
    icon: '🤗',
  },
  
  // Environment & Sustainability
  {
    id: 'recycle',
    title: 'Recycling Habit',
    category: 'other',
    description: 'Recycle regularly',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 40,
    period: 'monthly',
    icon: '♻️',
  },
  {
    id: 'reduce_plastic',
    title: 'No Plastic Bags',
    category: 'other',
    description: 'Use reusable bags',
    target: 0,
    unit: 'bags',
    direction: 'decrease',
    points: 35,
    period: 'weekly',
    icon: '🛍️',
  },
  {
    id: 'plant_trees',
    title: 'Plant Trees',
    category: 'other',
    description: 'Help the environment',
    target: 10,
    unit: 'trees',
    direction: 'increase',
    points: 100,
    period: 'yearly',
    icon: '🌳',
  },
  {
    id: 'composting',
    title: 'Compost Waste',
    category: 'other',
    description: 'Start composting',
    target: 30,
    unit: 'days',
    direction: 'increase',
    points: 45,
    period: 'monthly',
    icon: '🗑️',
  },
];

/**
 * Get templates by category
 */
export const getTemplatesByCategory = (category: string): GoalTemplate[] => {
  return GOAL_TEMPLATES.filter(template => template.category === category);
};

/**
 * Get translated goal templates based on language
 */
export const getGoalTemplates = (language: Language = 'en'): GoalTemplate[] => {
  return GOAL_TEMPLATES_BASE.map(template => {
    const translation = getGoalTemplateTranslation(template.id, language);
    return {
      ...template,
      title: translation.title || template.title,
      description: translation.description || template.description,
    };
  });
};

// Export default English templates
export const GOAL_TEMPLATES = GOAL_TEMPLATES_BASE;

/**
 * Get a template by ID
 */
export const getTemplateById = (id: string, language: Language = 'en'): GoalTemplate | undefined => {
  const templates = getGoalTemplates(language);
  return templates.find(template => template.id === id);
};
